server:
   port: 8081

info:
   component: api Server
  
eureka:
  instance:
      hostname: localhost
      port: 8888
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


security:
   basic:
      enabled: false
                
logging:
   level:
      ROOT: INFO
      org.springframework.web: INFO
