#https://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html#spring-cloud-eureka-server
server:
  port: 8888
  
eureka:
  instance:
    hostname: localhost
  server:
    renewalPercentThreshold: 0.49
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO