spring:
  aop:
    proxyTargetClass: true
  application:
    name: api-gateway

server:
   port: 9090

info:
   component: Zuul Server
  
eureka:
  instance:
      hostname: localhost
      port: 8888
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


zuul:
   ignoredServices: '*'
   routes:
      api:
         path: /api/**
         serviceId: api-service
         stripPrefix: true
      oauth:
         sensitiveHeaders:
         path: /uaa/**
         serviceId: oauth2-server
         stripPrefix: false
   addProxyHeaders: true
   
security:
   oauth2:
      resource:
         jwt:
            key-value: |
               -----BEGIN PUBLIC KEY-----
               MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCNMzaGp8LaxddOTYQywlM9Csjr
               /dVcKUSF8p15sZDmerLXNQ006vVWa1AVK0XW1zCv3N45Wk+LgT83v/PZtD2qkM8v
               1qHoLkPU3kKYl6AYIgFvNcFnNuEUi4P2QIAMEBadqCatvzqKsP+WybSDe5fVFZ54
               0+gPisMfdASEOoDwDwIDAQAB
               -----END PUBLIC KEY-----

logging:
   level:
      ROOT: INFO
      org.springframework.security: DEBUG
