spring:
  aop:
    proxyTargetClass: true
  application:
    name: api-gateway

server:
   port: 9090

info:
   component: Zuul Server
  
eureka:
  instance:
      hostname: localhost
      port: 8888
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


zuul:
   ignoredServices: '*'
   routes:
      api:
         path: /api/**
         serviceId: api-service
         strip-prefix: true
      oauth:
         sensitiveHeaders:
         path: /uaa/**
         serviceId: oauth2-server
         strip-prefix: false
   add-proxy-headers: true
            
logging:
   level:
      ROOT: INFO
      org.springframework.security: DEBUG
